### ISSUE TITLE
Map doesn't work on physical pixel 4a android 12

### ISSUE THREAD

**Issue by Sean-Meyers** [CMPUT301W22T29/301-Project#96]
Will add more details later as I explore the bug in more detail but, for now make do with this:
![image](https://user-images.githubusercontent.com/78064035/169385916-ece794c3-8b24-43fe-a05e-cd6fc4665e61.png)

This probably has to do with physical devices not being guaranteed to get a satellite signal. If the provider can't figure out the phone's location, it will give up, and the variable that is supposed to have location data will just be null. This is why the issue never happens with an emulator, because an emulator will never fail to get a "satellite signal" or an exact enough location. I think this same issue may have been fixed for some other map related stuff in 301 Quirky, may need to look at that later.

**Comment by Sean-Meyers** [comment]
found in commit b80af4270fcfc504068c1f41270c46d16eab065a on JJ branch

**Comment by jJadsit** [comment]
I installed a Pixel 4a emulator running Android 12.0 with API 31, and the map did not crash.
From the bug report, a `GeoLocation` is being created with  `new GeoLocation(Location location)`, but the Location object being passed to it is null.
Therefore `locationManager.getCurrentLocation( ... )` on line 156 is returning a null location. I have no idea how MapController or LocationManager works, but the tests are inconsistent because the same setup emulated on my desktop seems to run fine.
If you are looking into this bug, I hope this (somehow) helps.
